### ISSUE TITLE
On STAGE_END, OnEventStageChangedFunction should include song list and aggregated choice data

### ISSUE THREAD

**Issue by sjawhar** [sjawhar/enchanted-brain#40]
## Expected Behavior
In the STAGE_END stage data, we need to include aggregated choices and song list for the user's app to visualize. It makes sense to pre-process the data so that each song also includes the aggregated choices that belong to it. In other words, the event should look something like this:

```js
{
  stageId: 'STAGE_END',
  songs: [
    {
      displayName: String,
      startTime: String,
      endTime: String,
      choiceType: String,  // CHOICE_COLOR || CHOICE_CHILLS
      choices: [
        // CHOICE_COLOR
        {
          timestamp: String,
          '#AB0000': Number,
          '#AB8000': Number,
          ...
        },
        // CHOICE_CHILLS
        {
          timestamp: String,
          sum: Number,
          count: Number,
        },
        ...
      ]
    }
    ...
  ]
}
```

`choices` should include elements of _either_ the CHOICE_COLOR or CHOICE_CHILLS format, but not both.

## Possible Solution
It seems to me that a natural place to put this is the OnEventStageChangedFunction. If the stageId is STAGE_END, grab the [AGGREGATE](https://github.com/sjawhar/enchanted-brain/wiki/Concert#aggregated-choices) and [SONG_LIST](https://github.com/sjawhar/enchanted-brain/wiki/Concert#song-information) records and include the necessary data in the new EVENT_STAGE record. That way, the data will be included both in the published message (#11) and if a user disconnects and reconnects during intermission (#13).

## Tasks
- [ ] Update docs
- [ ] Tests
- [ ] Code
- [ ] Check CloudFormation resources and permissions

**Comment by Borchardt** [comment]
Any concerns here about the one minute stagger window for aggregate data? Should we plan to try to wait until a minute after selections end to send this event? Or maybe build in logic to wait until 1 minute after the last end time in the song list before pulling data and publishing to callback?

**Comment by sjawhar** [comment]
We can wait. This is meant for the intermission, so there's no rush between the end of the chills song and the display of results.
