### ISSUE TITLE
Ensure necessary Dynamo items and attributes created on CFN stack deploy

### ISSUE THREAD

**Issue by Borchardt** [sjawhar/enchanted-brain#50]
TODO: Compile list of known requirements:
* empty maps for `colors`, `emotions`, and `chills` for `AGGREGATE` row
* `SONG_LIST` record with `songs` list

## Expected Behavior
Records and attributes necessary for writer Lambdas to function successfully created (if don't exist) on CFN deploy

## Current Behavior
These records and attributes have been added manually

## Possible Solution
TODO

## Tasks
TODO

**Comment by sjawhar** [comment]
If we can also have the Kinesis application start on deploy, that would be :+1:
